[phases.setup]
nixPkgs = ["nodejs", "chromium"]

[phases.install]
cmds = ["npm ci --production"]

[start]
cmd = "node index.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/var/nix/profiles/default/bin/chromium"
